name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy Artifacts
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Bundle
      uses: swiftwasm/swiftwasm-action@v5.7
      with:
        shell-action: carton bundle --product server-client --custom-index-page static/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Bundle
